### PR TITLE
Migrating from SQLLite to MYSQL

### PR DESCRIPTION
**Pull request by ravichandrasadineni**
Please review the changes and suggest changes if any.

### CODE REVIEW

**Comment by rpanah** [comment]
This pull request is a little too messy (files added and deleted, duplicate non-descriptive commit messages, etc.). You need to reset to the last commit before your own commit (do `git log`, and then do `git reset [the commit ID]`) and then do a clean `git add [file changed]` and `git commit`. After you're done, you can do a force push by running `git push origin [branch] --force`. This pull request will be automatically updated once you do so.

**_You do not need to close this pull request and/or submit a new pull request._**

To avoid having messy commits in the future, I would strongly advise you against doing `git add *` (what you've done here, apparently). Just add the files you have changed. If you aren't sure (or lost track of the files that have been changed), just run `git status`).

Also I think PostgreSQL is a better choice for the database. Can you change it to that?

Just do the steps above, and I'll review again.

**Comment by phillipa** [comment]
I thought we spent a while talking about this DB issue. Although I’m a bit hazy on what we converged on. PostgreSQL sounds about right.

Phillipa Gill, Assistant Professor
Dept. of Computer Science
Stony Brook University, SUNY
http://www.cs.stonybrook.edu/~phillipa <http://www.cs.stonybrook.edu/~phillipa>
http://www.nrg.cs.stonybrook.edu <http://www.nrg.cs.stonybrook.edu/>

**Comment by rpanah** [comment]
@ravichandrasadineni, also, you've done your coding in your master branch. I would suggest creating branches for each `fix` or `feature` by following these steps (assuming you have a remote added by doing `git remote add remote https://github.com/iclab/centinel-server`):

```
git checkout origin master
git pull remote master
```
`git branch fix/bug_fix_name` or `git branch feature/feature_name`

and
```
git checkout [branch_name]
```
and then do your coding in the newly-created branch. You can send pull requests from this branch from github's repo page.

**Comment by rpanah** [comment]
Talk to Himanshu (@Dexhub) about coding guidelines for the github repo as I've explained this to him in detail.

**Comment by ravichandrasadineni** [comment]
Working on it. Will follow your instructions and ammend thecommit accordingly.

**Comment by ravichandrasadineni** [comment]
And what should we do for the migration of the existing data to the newDB ? what are we planning to do on that ?

**Comment by phillipa** [comment]
We could think about migrating it. Not sire we've collected anything useful
yet. But Abbas would know more

**Comment by rpanah** [comment]
The results we've collected are not part of what is going to migrated. It's just a bunch of user records (usernames, passwords, etc.) and I can migrate those very easily.

**Comment by ravichandrasadineni** [comment]
@rpanah I am trying to push a new branch to  here. But i don't have permissions. Can you please give me permissions. Thanks

**Comment by rpanah** [comment]
@ravichandrasadineni, I said you don't need to close this pull request.
You can reset back to the last good commit **on the same branch**, do a force push, and then make more commits.
Refer to my last comments on this pull request.

**Comment by ravichandrasadineni** [comment]
@rpanah  I have not closed the pull request. When i did a force push removing the last two commits, it has automatically closed the pull request.

**Comment by rpanah** [comment]
I see. It's okay.

**Comment by ravichandrasadineni** [comment]
Can u please give me permission. So that i can push the branch and create a pull request. Thanks in advance

**Comment by rpanah** [comment]
You don't need administrative access to the repo to issue a pull request,
nor do you need to touch any branch on the original repo.
You can, however, modify branches in your own fork of this branch and send
a pull request from there.

**Pull request closed without merging**
